version: "24.0.7"

services:
  mvnspringboot:
    image: mvnspringboot:0.0.1
    ports:
      - 9091:8080
    environment:
      DB_URL: "jdbc:h2:tcp://h2db/compose-db;DB_CLOSE_DELAY=-1"
      DB_USERNAME: "fati"
      DB_PASSWORD: "fati"



  h2db:
    image: buildo/h2database
    ports:
      - 9092:8082
